version: '3'

services:
  backend:
    container_name: 'backend'
    build:
      context: backend
      dockerfile: Dockerfile
    networks:
      - backend
    env_file: .env
    restart: unless-stopped
    ports:
      - '4000:3000'
    depends_on:
      - postgres

  postgres:
    container_name: 'postgres'
    image: postgres:12.12-alpine
    networks:
      - backend
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata

  frontend:
    container_name: 'frontend'
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - '8081:80'

volumes:
  pg_data:
    driver: local


networks:
  backend: